# https://bandit.readthedocs.io/en/latest/config.html
# Skip test B101 because of issue https://github.com/PyCQA/bandit/issues/457
[tool.bandit]
tests = []
skips = ["B101"]

# https://pycqa.github.io/isort/
[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
skip_gitignore = true
skip_glob = [
    "*/docs/*",
    "*/*_pb2.py",
    "*/*_pb2_grpc.py",
]

# https://github.com/psf/black#configuration
[tool.black]
line-length = 120
target-version = ["py39"]

# https://docs.pytest.org/en/6.2.x/customize.html#configuration-file-formats
# https://docs.pytest.org/en/6.2.x/reference.html#configuration-options
# https://docs.pytest.org/en/6.2.x/reference.html#command-line-flags
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose --doctest-modules -ra --cov package_server"  # Consider adding --pdb or # --ignore=**/test_server.py
doctest_optionflags = "IGNORE_EXCEPTION_DETAIL"
testpaths = [
    "./servicer/tests",
]

# https://github.com/pytest-dev/pytest-cov
# https://github.com/nedbat/coveragepy
[tool.coverage.run]
omit = [
    "*/package_grpc/*_pb2*",
    "*/package_grpc/v*/*_pb2*",
    "*/package_server/__main__.py",
]

[tool.coverage.report]
fail_under = 100
show_missing = true
