# Send a Slack release notification.

name: Release Notifications
on:
  release:
    types: [published]
jobs:
  slack:
    name: Slack release notification
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text": "${{ github.event.repository.name }} published a new release ${{ github.event.release.tag_name }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*${{ github.event.repository.name }}* published a new release <${{ github.event.release.html_url }}|${{ github.event.release.tag_name }}>"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
